services:
  # web:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   restart: always
  #   stdin_open: true 
  #   tty: true  
    # environment:
    #   DB_HOST: db 
  db:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root 
      POSTGRES_PASSWORD: root 